=== Alex-Gen/cgaWorkInProgress/XML/commenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
xmlns:c="http://www.ptollot/commenti.xml"
targetNamespace="http://www.ptollot/commenti.xml"
elementFormDefault="qualified" >

<element name="commenti">
    <complexType>
        <sequence>
            <element name="commento" maxOccurs="unbounded">
                <complexType>
                    <sequence>
                        <element name="user" type="string" />
                        <element name="post" type="string" />
                        <element name="data">
                            <simpleType>
                                <restriction base="string">
                                    <pattern value="[0-9]{2}-[0-9]{2}-[0-9]{4}" />
                                </restriction>
                            </simpleType>
                        </element>
                        <element name="contenuto" type="string" />
                    </sequence>
                </complexType>
            </element>
        </sequence>
    </complexType>
</element>

</schema>

=== Alex-Gen/cgaWorkInProgress/XML/commenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<commenti xmlns="http://www.ptollot/commenti.xml" xmlns:schemaLocation="http://serverConsulta/XML/commenti.xsd">
    
    <commento>
        <user>ciccio</user>
        <post>primo</post>
        <data>12-12-2014</data>
        <contenuto>Che bel Post!</contenuto>
    </commento>
    
<commento><user>io</user><post>post1</post><data> 24 Gen 2015 alle ore 13.59</data><contenuto>bla bla</contenuto></commento>
<commento><user>io</user><post>post1</post><data> 24 Gen 2015 alle ore 14.12</data><contenuto>concorrente finalmente!!</contenuto></commento><commento><user>io</user><post>post1</post><data> 24 Gen 2015 alle ore 14.12</data><contenuto>evviva evviva!! </contenuto></commento><commento><user>io</user><post>post1</post><data> 20 Feb 2015 alle ore 21.17</data><contenuto>dfds</contenuto></commento><commento><user>io</user><post>post1</post><data> 20 Feb 2015 alle ore 21.18</data><contenuto>mmm</contenuto></commento><commento><user>io</user><post>post1</post><data> 20 Feb 2015 alle ore 21.18</data><contenuto>mmm</contenuto></commento><commento><user>io</user><post>post</post><data> 20 Feb 2015 alle ore 22.12</data><contenuto/></commento><commento><user>io</user><post>post</post><data> 20 Feb 2015 alle ore 22.12</data><contenuto/></commento><commento><user>io</user><post>post</post><data> 20 Feb 2015 alle ore 22.13</data><contenuto/></commento><commento><user>io</user><post>post</post><data> 20 Feb 2015 alle ore 22.19</data><contenuto/></commento><commento><user>io</user><post>0</post><data> 20 Feb 2015 alle ore 22.20</data><contenuto>jjj</contenuto></commento><commento><user>io</user><post>0</post><data> 20 Feb 2015 alle ore 22.21</data><contenuto>OK</contenuto></commento><commento><user>io</user><post>0</post><data> 20 Feb 2015 alle ore 22.22</data><contenuto>OK</contenuto></commento><commento><user>io</user><post>post1</post><data> 20 Feb 2015 alle ore 22.23</data><contenuto>OK</contenuto></commento><commento><user>io</user><post>post1</post><data> 20 Feb 2015 alle ore 22.24</data><contenuto>OKduevolte</contenuto></commento><commento><user>io</user><post>post1</post><data> 20 Feb 2015 alle ore 22.26</data><contenuto>ciccia!!</contenuto></commento><commento><user>io</user><post>post1</post><data> 20 Feb 2015 alle ore 22.29</data><contenuto>ciaooooooooo</contenuto></commento><commento><user>io</user><post>post1</post><data> 20 Feb 2015 alle ore 22.32</data><contenuto>bubu</contenuto></commento><commento><user>io</user><post>posto2</post><data> 20 Feb 2015 alle ore 22.33</data><contenuto>bububu</contenuto></commento><commento><user>io</user><post>post2</post><data> 20 Feb 2015 alle ore 22.35</data><contenuto>ewew</contenuto></commento><commento><user>io</user><post>post2</post><data> 27 Feb 2015 alle ore 17.19</data><contenuto>ciao</contenuto></commento><commento><user>io</user><post>post2</post><data> 5 Mar 2015 alle ore 17.19</data><contenuto>ciao come stai?</contenuto></commento><commento><user>io</user><post>post2</post><data> 27 Apr 2015 alle ore 20.42</data><contenuto>sono gualtiero e adesso risolvo il problema costi anche saltare il cineforum</contenuto></commento><commento><user>io</user><post>post2</post><data> 29 Apr 2015 alle ore 20.57</data><contenuto>ciao</contenuto></commento><commento><user>io</user><post>post2</post><data> 29 Apr 2015 alle ore 20.57</data><contenuto> miaofndsugfnsdgislrgisaggrglvina,mdisadsaa regione Veneto ha approvato il nuovo bando della Consulta Giovani Alpago dal titolo "", che partirá ufficialmente da Gennaio 2015. "Sará un progetto che cercherá di fare, come minimo, quanto é giá stato fatto lo scorso anno" dice il neo-presidente della CGA Munaro Michael "Quello che ci preme di più è però far in modo che la gente torni a percepire la Consulta come un'entià presente e attiva sul territorio e non semplicemente come un qualcosa che si conosce semplicemente per sentito dire o perchè ci si vede recapitare a casa il famoso editoriale "l'Alpagone" ". Ed è proprio parlando di Alpagone che saltano fuori alcune delle novità in vista per il nuovo anno. L'Alpagone per stare al passo coi tempi, passerà al formato digitale e sarà possibile scaricarlo comodamente in formato PDF sul proprio PC o dispositivo mobile accedendo al sito ufa regione Veneto ha approvato il nuovo bando della Consulta Giovani Alpago dal titolo "", che partirá ufficialmente da Gennaio 2015. "Sará un progetto che cercherá di fare, come minimo, quanto é giá stato fatto lo scorso anno" dice il neo-presidente della CGA Munaro Michael "Quello che ci preme di più è però far in modo che la gente torni a percepire la Consulta come un'entià presente e attiva sul territorio e non semplicemente come un qualcosa che si conosce semplicemente per sentito dire o perchè ci si vede recapitare a casa il famoso editoriale "l'Alpagone" ". Ed è proprio parlando di Alpagone che saltano fuori alcune delle novità in vista per il nuovo anno. L'Alpagone per stare al passo coi tempi, passerà al formato digitale e sarà possibile scaricarlo comodamente in formato PDF sul proprio PC o dispositivo mobile accedendo al sito ufa regione Veneto ha approvato il nuovo bando della Consulta Giovani Alpago dal titolo "", che partirá ufficialmente da Gennaio 2015. "Sará un progetto che cercherá di fare, come minimo, quanto é giá stato fatto lo scorso anno" dice il neo-presidente della CGA Munaro Michael "Quello che ci preme di più è però far in modo che la gente torni a percepire la Consulta come un'entià presente e attiva sul territorio e non semplicemente come un qualcosa che si conosce semplicemente per sentito dire o perchè ci si vede recapitare a casa il famoso editoriale "l'Alpagone" ". Ed è proprio parlando di Alpagone che saltano fuori alcune delle novità in vista per il nuovo anno. L'Alpagone per stare al passo coi tempi, passerà al formato digitale e sarà possibile scaricarlo comodamente in formato PDF sul proprio PC o dispositivo mobile accedendo al sito ufa regione Veneto ha approvato il nuovo bando della Consulta Giovani Alpago dal titolo "", che partirá ufficialmente da Gennaio 2015. "Sará un progetto che cercherá di fare, come minimo, quanto é giá stato fatto lo scorso anno" dice il neo-presidente della CGA Munaro Michael "Quello che ci preme di più è però far in modo che la gente torni a percepire la Consulta come un'entià presente e attiva sul territorio e non semplicemente come un qualcosa che si conosce semplicemente per sentito dire o perchè ci si vede recapitare a casa il famoso editoriale "l'Alpagone" ". Ed è proprio parlando di Alpagone che saltano fuori alcune delle novità in vista per il nuovo anno. L'Alpagone per stare al passo coi tempi, passerà al formato digitale e sarà possibile scaricarlo comodamente in formato PDF sul proprio PC o dispositivo mobile accedendo al sito uf</contenuto></commento><commento><user>io</user><post>post2</post><data> 29 Apr 2015 alle ore 20.58</data><contenuto>gualtiero</contenuto></commento><commento><user>io</user><post>post2</post><data> 29 Apr 2015 alle ore 20.58</data><contenuto>fadfasfdsafds</contenuto></commento><commento><user>io</user><post>post1</post><data> 29 Apr 2015 alle ore 20.58</data><contenuto>cdcDSCvcSFC</contenuto></commento><commento><user>io</user><post>post2</post><data> 28 Mag 2015 alle ore 10.54</data><contenuto>sono Michael</contenuto></commento><commento><user>io</user><post>post2</post><data> 28 Mag 2015 alle ore 10.55</data><contenuto>fadfads</contenuto></commento><commento><user>io</user><post>post2</post><data> 28 Mag 2015 alle ore 10.55</data><contenuto>dasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDASdasfadsasfsAFASDAS&#13;
&#13;
&#13;
</contenuto></commento></commenti>
